version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: blackjack
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-network
    command: ["mysqld", "--bind-address=0.0.0.0"]


  mongo-db:
    image: mongo:6
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: blackjack
    ports:
      - "27017:27017"
    networks:
      - backend-network

  blackjack-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blackjack-api
    depends_on:
      - mysql-db
      - mongo-db
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:mysql://mysql-db:3306/blackjack
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: root
      SPRING_DATA_MONGODB_URI: mongodb://mongo-db:27017/blackjack
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge