version: "3.8"

services:
  blackjack-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blackjack-api
    depends_on:
      - mysql
      - mongo
    ports:
      - "8080:8080"
    networks:
      - blackjack-network

  mysql:
    image: mysql:8.0
    container_name: mysql-blackjack
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234A
      MYSQL_DATABASE: blackjack_db
      MYSQL_USER: ignasubirachs
      MYSQL_PASSWORD: 1234A
    networks:
      - blackjack-network

  mongo:
    image: mongo
    container_name: mongo-blackjack
    ports:
      - "27018:27017"
    networks:
      - blackjack-network

networks:
  blackjack-network:
    driver: bridge
