spring:
  application:
    name: blackjack-api

  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:mysql://localhost:3306/blackjack}
    username: ${SPRING_R2DBC_USERNAME:root}
    password: ${SPRING_R2DBC_PASSWORD:root}

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/blackjack}

server:
  port: 8080
  error:
    include-message: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

info:
  title: Blackjack API
  description: Reactive REST API for Blackjack
  version: 1.0.0
