spring:
  application:
    name: blackjack-api

    r2dbc:
      url: r2dbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}

  data:
    mongodb:
      uri: ${MONGO_URI}

  main:
    allow-bean-definition-overriding: true

server:
  error:
    include-message: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

info:
  title: Blackjack API
  description: API
  version: 1.0.0
