spring:

  application:
    name: blackjack-api

  r2dbc:
    url: r2dbc:mysql://localhost:3308/blackjack_db
    username: ignasubirachs
    password: 1234A

  data:
    mongodb:
      uri: mongodb://localhost:27017/blackjack-mongo
      database: blackjack-mongo

  main:
    allow-bean-definition-overriding: true

server:
  error:
    include-message: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

info:
  title: Blackjack API
  description: API
  version: 1.0.0
