spring:
  application:
    name: blackjack-api

  r2dbc:
    url: r2dbc:mysql://localhost:3309/blackjack_db
    username: ignasubirachs
    password: 1234A

  data:
    mongodb:
      uri: mongodb://localhost:27018/blackjack

  main:
    allow-bean-definition-overriding: true

server:
  port: 8080
  error:
    include-message: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

info:
  title: Blackjack API
  description: Reactive Blackjack API using Spring WebFlux, MongoDB and MySQL (R2DBC)
  version: 1.0.0
